{% set name = "activemq-cpp" %}
{% set version = "3.9.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/apache/activemq-cpp/archive/refs/tags/activemq-cpp-{{ version }}.tar.gz
  sha256: 3a56b526360155fd920f136b187ffb84942890b9b7e206976c81ef9f2ab2b11b
  patches:
    - testing.diff
    - remove-namespaced-includes.diff

build:
  number: 2
  skip: true  # [win]
  run_exports:
    # Not sure about ABI. Pin to x.x.x for now
    - {{ pin_subpackage(name, max_pin="x.x.x") }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - autoconf
    - automake
    - libtool
    - pkg-config
    - make
  host:
    - libapr
    - libaprutil
    - cppunit
    - openssl

test:
  commands:
    - test -f $PREFIX/bin/activemqcpp-config
    - activemqcpp-config --help
    - test -f $PREFIX/include/activemq/core/ActiveMQSession.h
    - test -f $PREFIX/include/cms/DeliveryMode.h
    - test -f $PREFIX/lib/libactivemq-cpp${SHLIB_EXT}

about:
  home: https://github.com/apache/activemq-cpp
  summary: 'ActiveMQ CPP is a messaging library that can use multiple protocols to talk to a MOM.'
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - isuruf
    - timkpaine
